#!/usr/bin/python3

# BUGS: Git operations aren't atomic, concurrency would be dicey!

import sys, os
import posixpath
import re
import subprocess

from subprocess import PIPE
from traceback import print_exception
from urllib.parse import urlparse, urlunparse

DOCROOT = "/var/gemini/shizdoc"
LOCALREPO = "/home/gmcapsule/shizdoc.git"


def main():
    ident = None
    if 'REMOTE_IDENT' in os.environ:
        ident = os.environ['REMOTE_IDENT']
    proto = "GEMINI"
    if 'SERVER_PROTOCOL' in os.environ:
        proto = os.environ['SERVER_PROTOCOL']

    try:
        if not ident_is_auth(ident):
            print("61 go away, you're not on the list\r")
        elif proto == 'TITAN':
            handle_titan()
        else:
            handle_gemini()
    except GeminiException as e:
        print(e.response)
        #sys.stdout.close()
        #raise e
        # gmcapsule won't actually issue our response if we exit
        # non-zero. Print traceback to stderr and exit successfully.
        print_exception(e, file=sys.stderr)
        exit(0)
    except BaseException as e:
        print("40 unknown error\r")
        #sys.stdout.close()
        #raise e
        # gmcapsule won't actually issue our response if we exit
        # non-zero. Print traceback to stderr and exit successfully.
        print_exception(e, file=sys.stderr)
        exit(0)

def ident_is_auth(ident):
    # Read in authorization file
    file = open("admin.ident", "r")
    auth = [ line.strip() for line in file.readlines() ]
    file.close()

    return ident in auth

def handle_delete():
    path = get_doc_path()

    # Display the results of deleting the file from git
    print("20 text/gemini\r")

    print(f"# DELETING {normalize_path_info(no_admin = True)}")
    print()
    redir = admin_redirect()
    print(f"=> {redir}")
    print()

    print("# Git rm")
    rmst, rmout = do_git('rm', get_doc_path())
    print(rmout, end = '')
    print(f"Exit: {rmst}")
    print()

    print("# Git commit")
    commitst, commitout = do_git('commit', '-m', "DEL " + os.environ['PATH_INFO'])
    print(commitout, end = '')
    print(f"Exit: {commitst}")

def handle_titan():
    length = os.environ['CONTENT_LENGTH']
    if (not length) or int(length) == 0:
        handle_delete()
        return

    file = get_titan_file() # (may throw exception)

    # Copy input to the opened-for-write file
    eol = True # let empty uploads be empty
    revmsg = []
    for line in sys.stdin:
        if line.startswith("!revmsg "):
            # commit message directives
            revmsg.append('-m')
            revmsg.append(line[len("!revmsg "):].strip())
        else:
            file.write(line)
        eol = line.endswith("\n")
    if not eol:
        file.write('\n')
    file.close()

    addst, addout = do_git('add', get_doc_path())
    if addst == 0:
        if len(revmsg) >= 2:
            revmsg[1] = os.environ['PATH_INFO'] + ": " + revmsg[1]
        else:
            revmsg.insert(0, os.environ['PATH_INFO'])
            revmsg.insert(0, '-m')
        commitst, commitout = do_git('commit', *revmsg)

    if addst == 0 and commitst == 0:
        redir = admin_redirect()
        print("30 " + redir)
        return

    # Display the results of committing the new file
    errpg = "20 text/gemini\r\n"

    errpg += f"# {normalize_path_info(no_admin = True)}: git ERROR occurred!\n"
    errpg += "\n"
    redir = admin_redirect()
    errpg += f"=> {redir}\n"
    errpg += "\n"

    errpg += "# Git add\n"
    errpg += addout
    errpg += f"Exit: {addst}\n"
    errpg += "\n"

    if commitout is not None:
        errpg += "# Git commit\n"
        errpg += commitout
        errpg += f"Exit: {commitst}\n"

    print(errpg)

def do_git(cmd, *args):
    argstr = ""
    for arg in args:
        argstr += f" {shquot(arg)}"
    cmdstr = "HOME=/dev/null; export LC_ALL=C GIT_DIR={} GIT_WORK_TREE={}; exec 2>&1 </dev/null; set -x; git {} {}".format(
        shquot(LOCALREPO),
        shquot(DOCROOT),
        shquot(cmd),
        argstr
    )

    # TODO: eliminate use of shell = True?
    proc = subprocess.run(cmdstr, stdout=PIPE, shell = True)

    # Program output is in bytes. We want a string.
    # We set LC_ALL=C to ascii, but it's still possible some stray bytes could
    # could appear.
    return proc.returncode, proc.stdout.decode("us-ascii", "backslashreplace")

def shquot(msg):
    val = re.sub("'", """'"'"'""", msg)
    val = f"'{val}'"
    return val

def handle_gemini():
    if not os.environ['PATH_INFO'].endswith('/'):
        # Redirect to slash-ending version
        redir = gemini_redirect()
        print(f"30 {redir}\r")

    page = get_page_view()
    page.print_response()

def get_titan_file():
    path = get_doc_path()
    dir = os.path.dirname(path)
    os.makedirs(dir, exist_ok=True) # consider umask 0o770?

    file = open(path, "w")
    return file

def normalize_path_info(no_admin = False):
    # Get the path atop our CGI script pathname
    path = ""
    if 'PATH_INFO' in os.environ:
        path = os.environ['PATH_INFO']
    envpath = path
    es = path.endswith("/")

    # Normalize it, resolving any .. or the like
    path = posixpath.normpath(path)
    if es and not path.endswith("/"):
        path += "/"

    # Make extra-sure that there is no '..' component to escape doc root
    if '..' in path.split(sep='/'):
        raise Exception(f"sneaky path {envpath}")

    # Ensure it starts with a leading slash
    if not path.startswith("/"):
        path = "/" + path

    # Strip out any leading "/:admin"
    if no_admin:
        pfx = "/:admin"
        if path.startswith(pfx + "/") or path == pfx:
            path = path[len(pfx):]

    return path

CACHED_DOC_PATH = None
def get_doc_path():
    global CACHED_DOC_PATH
    if CACHED_DOC_PATH is not None:
        return CACHED_DOC_PATH
    path = normalize_path_info(no_admin = True)
    # Remove any leading slashes
    while path.startswith('/'):
        path = path[1:]

    path = os.path.join(DOCROOT, path, "index.gmi")

    CACHED_DOC_PATH = path
    return path

def gemini_redirect(path_pfx = "", no_admin = False, proto = "gemini"):
    path = normalize_path_info(no_admin)
    if not path.endswith("/"):
        path += "/"
    path = path_pfx + path

    scrnam = ""
    if "SCRIPT_NAME" in os.environ:
        scrnam = os.environ["SCRIPT_NAME"]
        if not scrnam.startswith("/"):
            scrnam = "/" + scrnam
    path = scrnam + path

    redir = proto + "://"
    redir += os.environ["SERVER_NAME"]

    if "SERVER_PORT" in os.environ and os.environ["SERVER_PORT"] != "1965":
        redir += ":" + os.environ["SERVER_PORT"]
    redir += path

    return redir

def get_edit_link():
    return gemini_redirect(no_admin = True, proto = "titan") + ";edit"

def admin_redirect():
    # Ensure it gets an :admin URL (and strip out any existing)
    return gemini_redirect(path_pfx = "/:admin", no_admin = True)

def get_page_view():
    doc = get_doc_path()
    if ("TITAN_EDIT" in os.environ) and os.environ["TITAN_EDIT"]:
        return EditPageView(doc)
    elif os.environ['PATH_INFO'].startswith("/:admin/"):
        return AdminPageView(doc)
    else:
        return NormalPageView(doc)

class PageView():
    """PageView (base class)"""

    def print_response():
        """print the response for this page view"""
        raise(Exception("PageView base class used"))

class FileBackedPageView(PageView):
    """Base class for page views that are backed by an on-disk file"""

    def __init__(self, docpath):
        """Initialize a FileBackedPageView, with an optional path to the page's contents"""
        self._path = docpath

    def exists(self):
        """returns True if self.path() exists"""
        return os.path.exists(self._path)

    def path(self):
        """returns the page doc's path passed to the constructor"""
        return self._path

    def raw_text(self, encoding = "utf-8", errors = 'replace'):
        """generator for the lines of text in the file that backs this page view. Throws an exception if file does not exist."""
        file = open(self.path(), "r", encoding = encoding, errors = errors)
        if not file:
            raise FileNotFoundError(f"file not found: {self.path()}")
        return iterate_and_close(file)

    def print_response(self):
        try:
            text = self.raw_text()
            print("20 text/gemini\r")
            for line in text:
                print(line, end = "")
        except FileNotFoundError as e:
            print("51 not found\r")

def iterate_and_close(file):
    for line in file:
        yield line
    file.close()

class NormalPageView(FileBackedPageView):
    pass

class EditPageView(FileBackedPageView):
    pass

class AdminPageView(FileBackedPageView):
    def print_response(self):
        try:
            text = self.raw_text()
        except FileNotFoundError as e:
            text = None
        print("20 text/gemini\r")
        print(f"### Admin controls: {normalize_path_info(no_admin = True)}")
        path = normalize_path_info(no_admin = True)
        if text is not None:
            self._print_commit()
            print(f"=> {gemini_redirect(no_admin = True)} View {path}")
            print(f"=> {get_edit_link()} Edit {path}")
        else:
            print(f"=> {get_edit_link()} Create new page at {path}")
        print()
        self._print_directory()
        print()
        print("### Page content:")
        if text is not None:
            # Print the page content
            for line in text:
                if line.startswith("=>"):
                    line = self._adminify_link(line)
                print(line, end = "")

    def _adminify_link(self, line):
        """Transform relative links within the doctree, to :admin links"""
        fields = line.split()
        link = fields[1]
        parsed = urlparse(link)
        if parsed.scheme:
            return line
        path = parsed.path
        scrnam = os.environ['SCRIPT_NAME']
        pfx = os.environ['GEMINI_URL_PATH']
        path = posixpath.join(pfx, path)
        path = posixpath.normpath(path)

        if (path == scrnam
                or (path.startswith(scrnam + "/"))):
            path = path[len(scrnam):] # remove up to the start of PATH_INFO
            adm = "/:admin"
            if path == adm or path.startswith(adm + "/"):
                return line # link was already adminified!
            path = scrnam + "/:admin" + path
            fields[1] = urlunparse((
                parsed.scheme,
                parsed.netloc,
                path,
                parsed.params,
                parsed.query,
                parsed.fragment
            ))
            line = " ".join(fields) + "\n"
            return line
        else:
            return line

    def _print_directory(self):
        path = normalize_path_info(no_admin = True)
        while path.startswith("/"): path = path[1:]
        if path.endswith("/"): path = path[:-1]
        st, out = do_git('ls-tree', "HEAD:" + path)
        subdirs = []
        if st == 0:
            for line in out.split("\n"):
                fields = line.split(maxsplit = 3)
                if len(fields) != 4:
                    continue
                if fields[1] == "tree":
                    subdirs.append(fields[3] + "/")
        if len(subdirs) == 0:
            print("(no sub-entries found)")
        else:
            p = f"/{path}/"
            if p == "//": p = "/"
            print(f"Entries under {p}:")
            for sub in subdirs:
                print(f"=> {sub}")

    def _print_commit(self):
        path = normalize_path_info(no_admin = True)
        while path.startswith("/"): path = path[1:]
        if path.endswith("/"): path = path[:-1]
        st, out = do_git("log", '-n', '1', '--', path)
        if st == 0:
            print("```")
            lines = out.split("\n")
            lines = [lines[1]] + lines[3:]
            print("\n".join(lines))
            print("```")

class GeminiException(Exception):
    def __init__(self, code, msg):
        self.response = str(code) + " " + msg + "\r"
        super().__init__(self.response)

if __name__ == '__main__':
    main()
