#!/usr/bin/python3

# BUGS: Git operations aren't atomic, concurrency would be dicey!

import sys, os
import posixpath
import re
import subprocess

from subprocess import PIPE
from traceback import print_exception

DOCROOT = "/var/gemini/shizdoc"
LOCALREPO = "/home/gmcapsule/shizdoc.git"

def main():
    ident = None
    if 'REMOTE_IDENT' in os.environ:
        ident = os.environ['REMOTE_IDENT']
    proto = "GEMINI"
    if 'SERVER_PROTOCOL' in os.environ:
        proto = os.environ['SERVER_PROTOCOL']

    try:
        if not ident_is_auth(ident):
            print("61 go away, you're not on the list\r")
        elif proto == 'TITAN':
            handle_titan()
        else:
            handle_gemini()
    except GeminiException as e:
        print(e.response)
        #sys.stdout.close()
        #raise e
        # gmcapsule won't actually issue our response if we exit
        # non-zero. Print traceback to stderr and exit successfully.
        print_exception(e, file=sys.stderr)
        exit(0)
    except BaseException as e:
        print("40 unknown error\r")
        #sys.stdout.close()
        #raise e
        # gmcapsule won't actually issue our response if we exit
        # non-zero. Print traceback to stderr and exit successfully.
        print_exception(e, file=sys.stderr)
        exit(0)

def ident_is_auth(ident):
    # Read in authorization file
    file = open("admin.ident", "r")
    auth = [ line.strip() for line in file.readlines() ]
    file.close()

    return ident in auth

def handle_delete():
    path = get_doc_path()

    # Display the results of deleting the file from git
    print("20 text/gemini\r")

    print(f"# DELETING {os.environ['PATH_INFO']}")
    print()
    redir = gemini_redirect()
    print(f"=> {redir}")
    print()

    print("# Git rm")
    rmst, rmout = do_git('rm', get_doc_path())
    print(rmout, end = '')
    print(f"Exit: {rmst}")
    print()

    print("# Git commit")
    commitst, commitout = do_git('commit', '-m', "DEL " + os.environ['PATH_INFO'])
    print(commitout, end = '')
    print(f"Exit: {commitst}")

def handle_titan():
    length = os.environ['CONTENT_LENGTH']
    if (not length) or int(length) == 0:
        handle_delete()
        return

    file = get_titan_file() # (may throw exception)

    # Copy input to the opened-for-write file
    eol = True # let empty uploads be empty
    revmsg = []
    for line in sys.stdin:
        if line.startswith("!revmsg "):
            # commit message directives
            revmsg.append('-m')
            revmsg.append(line[len("!revmsg "):].strip())
        else:
            file.write(line)
        eol = line.endswith("\n")
    if not eol:
        file.write('\n')
    file.close()

    addst, addout = do_git('add', get_doc_path())
    if addst == 0:
        if len(revmsg) >= 2:
            revmsg[1] = os.environ['PATH_INFO'] + ": " + revmsg[1]
        else:
            revmsg.insert(0, os.environ['PATH_INFO'])
            revmsg.insert(0, '-m')
        commitst, commitout = do_git('commit', *revmsg)

    if addst == 0 and commitst == 0:
        redir = gemini_redirect()
        print("30 " + redir)
        return

    # Display the results of committing the new file
    errpg = "20 text/gemini\r\n"

    errpg += f"# {os.environ['PATH_INFO']}: git ERROR occurred!\n"
    errpg += "\n"
    redir = gemini_redirect()
    errpg += f"=> {redir}\n"
    errpg += "\n"

    errpg += "# Git add\n"
    errpg += addout
    errpg += f"Exit: {addst}\n"
    errpg += "\n"

    if commitout is not None:
        errpg += "# Git commit\n"
        errpg += commitout
        errpg += f"Exit: {commitst}\n"

    print(errpg)

def do_git(cmd, *args):
    argstr = ""
    for arg in args:
        argstr += f" {shquot(arg)}"
    cmdstr = "HOME=/dev/null; export LC_ALL=C; exec 2>&1 </dev/null; set -x; git --git-dir={} --work-tree={} {} {}".format(
        shquot(LOCALREPO),
        shquot(DOCROOT),
        shquot(cmd),
        argstr
    )

    # TODO: eliminate use of shell = True?
    proc = subprocess.run(cmdstr, stdout=PIPE, shell = True)

    # Program output is in bytes. We want a string.
    # We set LC_ALL=C to ascii, but it's still possible some stray bytes could
    # could appear.
    return proc.returncode, proc.stdout.decode("us-ascii", "backslashreplace")

def shquot(msg):
    val = re.sub("'", """'"'"'""", msg)
    val = f"'{val}'"
    return val

def handle_gemini():
    path = get_doc_path()
    exists = os.path.exists(path)

    if exists:
        file = open(path, "r")
        print("20 text/gemini\r")
        for line in file:
            print(line, end="")
    else:
        print("20 text/plain\r")
        print("No file here - available!")

def get_titan_file():
    path = get_doc_path()
    dir = os.path.dirname(path)
    os.makedirs(dir, exist_ok=True) # consider umask 0o770?

    file = open(path, "w")
    return file

def get_doc_path():
    # Get the path atop our CGI script pathname
    path = ""
    if 'PATH_INFO' in os.environ:
        path = os.environ['PATH_INFO']
    envpath = path

    # Normalize it, resolving any .. or the like
    path = posixpath.normpath(path)

    # Make extra-sure that there is no '..' component to escape doc root
    if '..' in path.split(sep='/'):
        raise Exception(f"sneaky path {envpath}")

    # Remove any leading slashes
    while path.startswith('/'):
        path = path[1:]

    path = os.path.join(DOCROOT, path, "index.gmi")

    return path

def gemini_redirect():
    if "GEMINI_URL_PATH" in os.environ:
        path = os.environ["GEMINI_URL_PATH"]
    else:
        path = os.environ["TITAN_URL_PATH"]
    if not path.endswith("/"):
        path += "/"
    if not path.startswith("/"):
        path = "/" + path

    redir = "gemini://"
    redir += os.environ["SERVER_NAME"]

    if "SERVER_PORT" in os.environ and os.environ["SERVER_PORT"] != "1965":
        redir += ":" + os.environ["SERVER_PORT"]
    redir += path

    return redir

class GeminiException(Exception):
    def __init__(self, code, msg):
        self.response = str(code) + " " + msg + "\r"
        super().__init__(self.response)

if __name__ == '__main__':
    main()
